#!/bin/bash
#
# Workflow:
# git co -b my-branch --track net-next/main
# vim ...
# git a .
# git cm -m "my patch"
#
# # clang-format each patch in a git rebase --exec:
# patches clang_format
#
# # Creates patches under patches.my-branch/ to review what they look like:
# patches create -v 1
#
# # Run all non-build presubmits (faster):
# patches presubmit_quick
#
# # Run all the checks including builds (slow):
# patches presubmit
#
# # Run a set of nipa tests:
# patches patches nipa_test patch/deprecated_api,patch/verify_signedoff
#
# # Send the patches:
# patches send -v 1
#
# # Run all the presubmits and send the patches without confirming:
# patches send_no_confirm -v 1

set -e

TEST="${TEST:-0}"
RFC="${RFC:-0}"
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

head=$(git rev-parse --abbrev-ref --symbolic-full-name HEAD)
parent=$(git rev-parse --abbrev-ref --symbolic-full-name "@{u}")
tree="${parent%/*}"

if [[ "$tree" != "net" && "$tree" != "net-next" ]]; then
	echo patches only supports net and net-next trees at the moment, detected invalid tree called: $tree
	exit 1
fi

echoerr() { cat <<< "$@" 1>&2; }

function create() {
	rm -rf "patches.$head"/*.patch

	local cover_letter=
	local files=""
	local range=""
	local to=""
	local cc=""

	for commit in $(git rev-list "$head" --max-count=50); do
		if ! git show "$commit" --oneline | grep -q "not-for-review"; then
			break;
		fi
	done

	range="$parent..$commit"

	count=$(git rev-list --count "$range")
	if [[ "$count" -lt 1 ]]; then
		echo "Not enough commits in range: $count"
		exit 1
	fi

	if git config branch."$head".description > .description.txt &&
	   [[ $count -gt 1 ]]; then
		cover_letter="--cover-letter \
			--cover-from-description=auto \
			--description-file=.description.txt"
	fi

	to=$(git diff "$range" | ./scripts/get_maintainer.pl \
		--no-git-fallback --norolestats -nom -nor --nomoderated \
		--nomultiline)

	cc=$(git diff "$range" | ./scripts/get_maintainer.pl \
		--git-min-percent 25 --norolestats -nol --nomoderated \
		--nomultiline)

	if [[ $RFC == 0 ]]; then
		PREFIX="PATCH $tree"
	else
		PREFIX="PATCH RFC $tree"
	fi

	files=$(git format-patch \
		--base "$parent" \
		-o "patches.$head" \
		"$range" \
		$cover_letter \
		--to="$to" \
		--cc="$cc" \
		--subject-prefix="$PREFIX" \
		"$@")

	# Delete change-id
	for file in $files; do
		sed '/Change-Id:/d' "$file" -i
	done

	echo "$files"
}

send() {
	local files=""

	files=$(create "$@")
	CONFIRM=${CONFIRM:-}

	if [[ $TEST == 0 ]]; then
		DRY_RUN=
	else
		DRY_RUN="--dry-run"
	fi

	yes | git send-email $files --cc-cover --8bit-encoding=UTF-8 $CONFIRM $DRY_RUN

	git tag "$(date +%F-%s)-$head-${FUNCNAME[0]}"
}

# Runs a command on each patch
cmd_each_patch() {
	local cmd="$1"

	echo
	echo "rebasing exec $cmd"
	git rebase --exec \
		"git show | grep -q \"not-for-review\" || $cmd" \
		"$parent"
}

build_each_patch() {
	make mrproper

	touch .first_in_series

	cmd_each_patch "PATCHES_CONFIG=\"$SCRIPT_DIR/configs/test.config\" ~/patches/build_patch_with_checks.sh"

	echo "Test build patches succeeded"
}

clang_format() {
	cmd_each_patch "git diff -U0 --no-color HEAD~ | /usr/lib/clang-format/clang-format-diff.py -i -p1"
}

check_behind() {
	git fetch "$tree"

	if git status -sb --ahead-behind | head -n 1 \
					 | grep -q behind; then
		echo your branch is behind its upstream. you gotta rebase.
		exit 1
	fi
}

presubmit_quick() {
	check_behind

	nipa_test "" "patch/build_32bit,patch/build_tools,patch/build_clang,patch/build_allmodconfig_warn,patch/build_clang_rust"
}

presubmit() {
	check_behind

	nipa_test "" ""

	git tag "$(date +%F-%s)-$head-${FUNCNAME[0]}"
}

send_no_confirm() {
	presubmit

	CONFIRM="--confirm=never" send "$@"
}

nipa_test() {
	local includes="$1"
	local excludes="$2"

	create

	cat > nipa.config <<EOF
		[log]
		type = stdout
		path = none
		file = none

		[results]
		dir = ./patches.nipa/results

		[dirs]
		tests = $SCRIPT_DIR/nipa/tests

		[tests]
		include = $includes
		exclude = patch/signed,$excludes
EOF

	rm -rf ./patches.nipa/
	mkdir -p ./patches.nipa/

	git branch -D nipa-scratch || true
	git checkout -b nipa-scratch

	"$SCRIPT_DIR"/nipa/ingest_mdir.py \
	  --mdir "$(pwd)"/patches."$head" \
	  --tree "$(pwd)" --tree-name "$tree" --tree-branch "$tree"/main

	git checkout "$head" -q

	local ret=0
	for retcode in $(find patches.nipa -iname retcode); do
		rettemp="$(cat "$retcode")"
		if [[ $rettemp == "250" ]]; then
			echo Check warned: "$retcode"
		elif [[ $rettemp != "0" ]]; then
			echo Check failed: "$retcode"
			ret=$rettemp
		fi
	done

	if [[ $ret == 0 ]]; then
		exit "$ret"
	fi
}

command="$1"
shift

if [ "$command" == "create" ]; then
	create "$@"
elif [ "$command" == "send" ]; then
	send "$@"
elif [ "$command" == "send_no_confirm" ]; then
	send_no_confirm "$@"
elif [ "$command" == "build_each_patch" ]; then
	build_each_patch "$@"
elif [ "$command" == "presubmit" ]; then
	presubmit "$@"
elif [ "$command" == "presubmit_quick" ]; then
	presubmit_quick "$@"
elif [ "$command" == "clang_format" ]; then
	clang_format "$@"
elif [ "$command" == "nipa_test" ]; then
	nipa_test "$@"
fi
